# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SoapBoxTV' do
pod 'AFNetworking'
pod 'OpenTok'
pod 'SIOSocket', '~> 0.2.0'
end

target 'SoapBoxTVTests' do

end

